<a href="https://colab.research.google.com/github/swarup1606/DATA_SCIENCE_INTERNSHIP/blob/main/Iris_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

# Read the Iris dataset
df = pd.read_csv("Iris.csv")

# Display the DataFrame
print(df)
# Display the shape of the DataFrame
print(df.shape)
# Display the first few rows of the DataFrame
print(df.head())
# Display the last few rows of the DataFrame
print(df.tail())
# Display the summary statistics of the DataFrame
print(df.describe())

# Calculate sum, mean, median, min, and max of Sepal Length
sum_data = df["SepalLengthCm"].sum()
mean_data = df["SepalLengthCm"].mean()
median_data = df["SepalLengthCm"].median()
min_data = df["SepalLengthCm"].min()
max_data = df["SepalLengthCm"].max()


      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  

In [ ]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Read the CSV file into a DataFrame
df = pd.read_csv("Data.csv")

# Print the DataFrame before scaling and one-hot encoding
print("Before scaling and one-hot encoding:")
print(df)

# Initialize the MinMaxScaler
scaler = MinMaxScaler()

# Scale the 'Age' and 'Salary' columns
df[['Age', 'Salary']] = scaler.fit_transform(df[['Age', 'Salary']])

# One-hot encode the 'Purchased' column
df = pd.get_dummies(df, columns=['Purchased'], prefix='Purchased')

# Print the DataFrame after scaling and one-hot encoding
print("\nAfter scaling and one-hot encoding:")
print(df)


Before scaling and one-hot encoding:
   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

After scaling and one-hot encoding:
   Country       Age    Salary  Purchased_No  Purchased_Yes
0   France  0.739130  0.685714          True          False
1    Spain  0.000000  0.000000         False           True
2  Germany  0.130435  0.171429          True          False
3    Spain  0.478261  0.371429          True          False
4  Germany  0.565217       NaN         False           True
5   France  0.347826  0.285714         False           True
6    Spain       NaN  0.114286          True          False
7   France  0.913043  0.885714         False      

In [ ]:
import numpy as np
from sklearn import preprocessing
Input_data = np.array([[2.1, -1.9, 5.5],
 [-1.5, 2.4, 3.5],
 [0.5, -7.9, 5.6],
 [5.9, 2.3, -5.8]])
data_binarized = preprocessing.Binarizer(threshold=0.5).transform(Input_data)
print("\nBinarized data:\n", data_binarized)


Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [ ]:
import numpy as np
from sklearn import preprocessing
input_data = np.array([[2.1, -1.9, 5.5],
[-1.5, 2.4, 3.5],
 [0.5, -7.9, 5.6],
 [5.9, 2.3, -5.8]])
print("Mean =", input_data.mean(axis=0))
print("Stddeviation =", input_data.std(axis=0))
data_scaled = preprocessing.scale(input_data)
print("Mean_removed =", data_scaled.mean(axis=0))
print("Stddeviation_removed =", data_scaled.std(axis=0))

Mean = [ 1.75  -1.275  2.2  ]
Stddeviation = [2.71431391 4.20022321 4.69414529]
Mean_removed = [1.11022302e-16 0.00000000e+00 0.00000000e+00]
Stddeviation_removed = [1. 1. 1.]


In [ ]:
import numpy as np
from sklearn import preprocessing
input_data = np.array([[2.1, -1.9, 5.5],
[-1.5, 2.4, 3.5],
 [0.5, -7.9, 5.6],
 [5.9, 2.3, -5.8]])
data_scaler_minmax = preprocessing.MinMaxScaler(feature_range=(0,1))
data_scaled_minmax = data_scaler_minmax.fit_transform(input_data)
print("\nMin max scaled dat:\n", data_scaled_minmax)


Min max scaled dat:
 [[0.48648649 0.58252427 0.99122807]
 [0.         1.         0.81578947]
 [0.27027027 0.         1.        ]
 [1.         0.99029126 0.        ]]


In [ ]:
import numpy as np
from sklearn import preprocessing
input_data = np.array([[2.1, -1.9, 5.5],
[-1.5, 2.4, 3.5],
 [0.5, -7.9, 5.6],
 [5.9, 2.3, -5.8]])
data_normalized_l1 = preprocessing.normalize(input_data, norm='l1')
print("\nNoramlized Data:\n", data_normalized_l1)


Noramlized Data:
 [[ 0.22105263 -0.2         0.57894737]
 [-0.2027027   0.32432432  0.47297297]
 [ 0.03571429 -0.56428571  0.4       ]
 [ 0.42142857  0.16428571 -0.41428571]]


In [ ]:
import numpy as np
from sklearn import preprocessing
input_data = np.array([[2.1, -1.9, 5.5],
[-1.5, 2.4, 3.5],
 [0.5, -7.9, 5.6],
 [5.9, 2.3, -5.8]])
data_normalized_l2 = preprocessing.normalize(input_data, norm='l2')
print("\nNoramlized Data:\n", data_normalized_l2)


Noramlized Data:
 [[ 0.33946114 -0.30713151  0.88906489]
 [-0.33325106  0.53320169  0.7775858 ]
 [ 0.05156558 -0.81473612  0.57753446]
 [ 0.68706914  0.26784051 -0.6754239 ]]
